project:
  description: Simple command line script accelerator
  author:
    name: Rob Lauer
    mailto: rclauer@gmail.com
pm_module: CLI::Simple
min-perl-version: 5.010
dependencies:
  test_requires: test-requires
  requires: requires
path:
  pm_module: lib
  tests: t
  exe_files: bin
  scripts: bin
extra-files:
  - ChangeLog
  - README.md
provides:
  - CLI::Simple::Constants
  - CLI::Simple::Utils
  - CLI::Simple::Helpers
  - CLI::Simple::DumpSpec
  - CLI::Simple::Migrate
  - CLI::Simple::Scaffold
resources:
  homepage: http://github.com/rlauer6/CLI-Simple
  bugtracker:
    web: http://github.com/rlauer6/CLI-Simple/issues
    mailto: rlauer6@comcast.net
  repository:
    url: git://github.com/rlauer6/CLI-Simple.git
    web: http://github.com/rlauer6/CLI-Simple
    type: 'git'
